### ISSUE TITLE
src/github.com/sandlbn/libvirt-go/cfuncs.go:6:10: fatal error: libvirt/libvirt.h: No such file or directory

### ISSUE THREAD

**Issue by Jerryhax** [rgbkrk/libvirt-go#129]
I get this in my console when I run a go project which import  shis libvirt-go.
>  github.com/sandlbn/libvirt-go
> src/github.com/sandlbn/libvirt-go/cfuncs.go:6:10: fatal error: libvirt/libvirt.h: No such file or directory
>  #include <libvirt/libvirt.h>
>           ^~~~~~~~~~~~~~~~~~~
> compilation terminated.

what‘s wrong？what should i do?

**Comment by berrange** [comment]
FYI, this repo is deprecated now in favour of using   https://github.com/libvirt/libvirt-go   which took this initial work upto 100% API coverage.

That said, your error message is caused by missing the native libvirt development header files. You need to install libvirt-devel / libvirt-dev  packages.

**Comment by Jerryhax** [comment]
thanks reply，it works after I install libvirt-devel packages.
